
flowchart TD
    start@{ shape: sm-circ, label: "Small start" }
    
    stage1Icon@{ icon: "mdi:abacus", form: "circle", pos: "b", h: 60 }
    boilIcon@{ icon: "mdi:wall", form: "circle", pos: "b", h: 60 }
    welcomeIcon@{ icon: "mdi:human-greeting-variant", form: "circle", pos: "b", h: 60 }
    dashIcon@{ icon: "mdi:menu-close", form: "circle", pos: "b", h: 60 }
    serverIcon@{ icon: "mdi:key-chain", form: "circle", pos: "b", h: 60 }
    promptsIcon@{ icon: "mdi:robot-happy", form: "circle", pos: "b", h: 60 }
    saveIcon@{ icon: "mdi:file-outline", form: "circle", pos: "b", h: 60 }
    clipsIcon@{ icon: "mdi:film", form: "circle", pos: "b", h: 60 }
    dataIcon@{ icon: "mdi:data-matrix-edit", form: "circle", pos: "b", h: 60 }
    scheduleIcon@{ icon: "mdi:calendar-clock-outline", form: "circle", pos: "b", h: 60 }
    messageIcon@{ icon: "mdi:format-list-text", form: "circle", pos: "b", h: 60 }
    resultIcon@{ icon: "mdi:package-variant-closed-check", form: "circle", pos: "b", h: 60 }

    stage2Icon@{ icon: "mdi:abacus", form: "circle", pos: "b", h: 60 }
    social1Icon@{ icon: "mdi:integrated-circuit-chip", form: "circle", pos: "b", h: 60 }
    social2Icon@{ icon: "mdi:login-variant", form: "circle", pos: "b", h: 60 }
    postIcon@{ icon: "mdi:post", form: "circle", pos: "b", h: 60 }

    stage1["stage1"]
    boil["boilerplate
    finished 2025_04_12"]
    welcome[welcome page in vue
    finished 2025_04_23]
    dash["dashboard menu in vue
    finished 2025_04_23"]
    server["server for auth keys in golang"]
    prompts["marketing data AI prompts in python or golang"]
    save["data save logic"]
    clips["python video clip editing"]
    data["marketing data page in vue"]
    schedule["AI generated marketing campaign schedule page"]
    message["AI generated video message editing page"]
    result["compiled video review page"]

    stage2["stage2"]
    social1["social media api integrations in golang"]
    social2["social media connect page in vue"]
    post["AI content posting page in vue"]

    start e1@===> stage1Icon
    start e2@===> stage2Icon
    
    stage1 e3@===> boilIcon
    boil e4@===> welcomeIcon
    welcome e5@===> dashIcon
    dash e6@===> serverIcon
    server e7@===> promptsIcon
    server e8@===> dataIcon
    prompts e9@===> dataIcon
    schedule e10@===> saveIcon
    save e11@===> messageIcon
    data e12@===> scheduleIcon
    schedule e13@===> messageIcon
    message e14@===> clipsIcon
    clips e15@===> resultIcon
    message e16@===> resultIcon

    stage2 e17@===> social1Icon
    social1 e18@===> social2Icon
    social2 e19@===> postIcon

    stage1Icon i@~~~ stage1
    boilIcon i@~~~ boil
    welcomeIcon i@~~~ welcome
    dashIcon i@~~~ dash
    serverIcon i@~~~ server
    promptsIcon i@~~~ prompts
    saveIcon i@~~~ save
    clipsIcon i@~~~ clips
    dataIcon i@~~~ data
    scheduleIcon i@~~~ schedule
    messageIcon i@~~~ message
    resultIcon i@~~~ result

    stage2Icon i@~~~ stage2
    social1Icon i@~~~ social1
    social2Icon i@~~~ social2
    postIcon i@~~~ post

    e1@{ animate: true }
    e2@{ animate: true }
    e3@{ animate: true }
    e4@{ animate: true }
    e5@{ animate: true }
    e6@{ animate: true }
    e7@{ animate: true }
    e8@{ animate: true }
    e9@{ animate: true }
    e10@{ animate: true }
    e11@{ animate: true }
    e12@{ animate: true }
    e13@{ animate: true }
    e14@{ animate: true }
    e15@{ animate: true }
    e16@{ animate: true }
    e17@{ animate: true }
    e18@{ animate: true }
    e19@{ animate: true }